name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: cd ../../../
    - run: cd Depends
    - run: bash LinuxDepends.sh
    - uses: actions/checkout@v2
    - run: ./autogen.sh
    - name: configure
      run: ./configure 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
